{% set name = "iadpython" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iadpython-{{ version }}.tar.gz
  sha256: 9efa69677a22450c140c4d13bd30b4f066a3158731c3a4497a7a989bac1dbc4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=44
  run:
    - matplotlib-base
    - numpy
    - scipy
    - python >=3.7
    - pytest
    - pyyaml

test:
  imports:
    - iadpython
  requires:
    - pytest
    - pip
  source_files:
    - tests/test_iad.py
  commands:
    - pip check
    - pytest tests/test_iad.py

about:
  home: https://github.com/scottprahl/iadpython.git
  summary: Python module for forward and inverse radiative transport calculations.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://iadpython.readthedocs.io/
  dev_url: https://github.com/scottprahl/iadpython

extra:
  recipe-maintainers:
    - scottprahl
